theme = "manjaro.com.cn"
baseurl = "/"
languageCode = "zh-cn"
title = "Manjaro - enjoy the simplicity"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true
publishDir = "../docs"
themesDir = "../.."
i18nDir = "../i18n/"
assetDir = "../static/"
DefaultContentLanguage = "zh-cn"

[markup.goldmark.renderer]
unsafe= true
# https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    website_version = "1.0.36"
    background = "/img/header.jpg"
    tint = "green"
    custom_js = []
    date_format = "2006年1月2日"
    meta_description = "Free fast and secure Linux based operating system for everyone, suitable replacement to Windows or MacOS with different Desktop Environments"
    meta_keywords = "manjaro linux, based on arch linux, free operating system"

    ### Download Menus
    editions = ["Official", "Community", "32Bit", "ARM", "Development"]
    arm_devices = ["PineBook Pro", "Raspberry Pi 4", "Rock Pi 4", "Rock Pro 64", "Khadas Vim 1", "Khadas Vim 3"]

[params.download_edition]
    download_x64_title = "64位版本"
    download_x86_title = "32位版本"
    download_button = "下载"
    download_button_minimal = "下载精简版"
    download_minimal_description = "精简版提供了一个基本的桌面环境，没有预装其他软件包。"
    download_x64_description = "只有64位课用于现代的硬件，如果你在寻找传统的32位请到点"
    download_x86_description = "如果您使用的是较旧的计算机，或者不确定计算机是否支持64位版本，请下载32位版本。"
    download_gpg = "下载 GPG 签名"
    download_torrent = "下载 Torrent 种子"

# --- Top Menu

[[menu.main]]
    name = "新闻"
    url = "/news/"
    pre = ""
    weight = 5

[[menu.main]]
    name = "商店"
    url = "#"
    pre = ""
    weight = 4
    identifier = "shop"

[[menu.main]]
    name = "捐助"
    pre = ""
    url = "/donate/"
    weight = 3 

[[menu.main]]
    name = "下载"
    url = "/download/"
    pre = ""
    weight = 1

[[menu.main]]
    name = "特性"
    url = "#"
    pre = ""
    weight = 2
    identifier = "features"

[[menu.main]]
    name = "更多"
    url = "#"
    pre = ""
    identifier = "more"
    weight = 6

#
# --- End Top Menu ---
#

# --- SubMenu More ---

[[menu.main]]
    name = "Packages"
    url = "https://repo.manjaro.org/"
    pre = ""
    weight = 3
    parent = "more"
    identifier = "packages"

[[menu.main]]
    name = "支持"
    url = "#"
    pre = ""
    weight = 2
    parent = "more"
    identifier = "support"

[[menu.main]]
    name = "关于"
    url = "#"
    pre = ""
    weight = 4
    parent = "more"
    identifier = "about"

[[menu.main]]
    name = "订阅列表"
    url = "#"
    pre = ""
    weight = 1
    identifier = "mailinglists"
    parent = "more"
#
# --- End SubMenu Others 
#

# --- SubMenu about ---

[[menu.main]]
    name = "团队"
    url = "/team/"
    pre = "<i class='fa fa-users'></i></i>"
    weight = 1
    parent = "about"

[[menu.main]]
    name = "Linux"
    url = "/linux/"
    pre = "<i class='fab fa-linux'></i></i>"
    weight = 2
    parent = "about"

# --- SubMenu Support ---

[[menu.main]]
    name = "第一步"
    url = "/support/firststeps/"
    pre = "<i class='fas fa-shoe-prints'></i></i>"
    weight = 1
    parent = "support"


[[menu.main]]
    name = "常见问题"
    url = "/support/commonproblems/"
    pre = "<i class='fas fa-ambulance'></i></i>"
    weight = 2
    parent = "support"


[[menu.main]]
    name = "用户指南"
    url = "/support/userguide/"
    pre = "<i class='fas fa-book-open'></i></i>"
    weight = 2
    parent = "support"


[[menu.main]]
    name = "论坛"
    url = "https://forum.manjaro.com.cn/"
    pre = "<i class='fas fa-hands-helping'></i></i>"
    weight = 3
    parent = "support"


[[menu.main]]
    name = "Wiki"
    url = "https://wiki.manjaro.org"
    pre = "<i class='fas fa-user-graduate'></i>"
    weight = 5
    parent = "support"

#
# --- End SubMenu Support 
#

# --- Submenu Shop ---

[[menu.main]]
    name = "商品 & 饰品"
    url = "https://shop.spreadshirt.de/manjaro/"
    pre = "<i class='fas fa-tshirt'></i>"
    weight = 1
    parent = "shop"


[[menu.main]]
    name = "Manjaro 贴纸"
    url = "https://linux-aarhus.dk/en/product-category/manjaro-en/stickers-en/"
    pre = "<i class='fas fa-ticket-alt'></i>"
    weight = 2
    parent = "shop"


[[menu.main]]
    name = "硬件-笔记本&电脑"
    url = "https://www.ubuntushop.be/index.php/en/opensource-notebooks/manjaro-notebooks.html"
    pre = "<i class='fas fa-desktop'></i>"
    weight = 5
    parent = "shop"


#[[menu.main]]
#    name = "Hardware - Spitfire"
#    url = "/hardware-spitfire"
#    pre = "<i class='fas fa-laptop'></i>"
#    weight = 4
#    parent = "shop"


# [[menu.main]]
#    name = "Hardware - Bladebook"
#    url = "/hardware-bladebook"
#    pre = ""
#    weight = 3
#    parent = "shop"

#
# --- End SubMenu Shop --- 
#

#
# --- Submenu Packages ---
#

[[menu.main]]
    name = "镜像"
    url = "https://repo.manjaro.org/"
    pre = "<i class='fas fa-globe'></i>"
    weight = 1
    parent = "packages"
    identifier = "mirrors"

[[menu.main]]
    name = "发现软件"
    url = "https://discover.manjaro.org/"
    pre = "<i class='fas fa-compass'></i>"
    weight = 1
    parent = "packages"
    identifier = "discover"

#
# --- end submenu ---
#

# --- Submenu Lists ---

[[menu.main]]
    name = "Security"
    url = "https://lists.manjaro.org/mailman/listinfo/manjaro-security"
    pre = "<i class='fas fa-envelope'></i>"
    weight = 1
    parent = "mailinglists"

[[menu.main]]
    name = "General"
    url = "https://lists.manjaro.org/mailman/listinfo/manjaro-general"
    pre = "<i class='fas fa-envelope'></i>"
    weight = 2
    parent = "mailinglists"


[[menu.main]]
    name = "Packages"
    url = "https://lists.manjaro.org/mailman/listinfo/manjaro-packages"
    pre = "<i class='fas fa-envelope'></i>"
    weight = 3
    parent = "mailinglists"


[[menu.main]]
    name = "Testing"
    url = "https://lists.manjaro.org/mailman/listinfo/manjaro-testing"
    pre = "<i class='fas fa-envelope'></i>"
    weight = 4
    parent = "mailinglists"


[[menu.main]]
    name = "Development"
    url = "https://lists.manjaro.org/mailman/listinfo/manjaro-dev"
    pre = "<i class='fas fa-envelope'></i>"
    weight = 5
    parent = "mailinglists"

[[menu.main]]
    name = "Mirrors"
    url = "https://lists.manjaro.org/mailman/listinfo/manjaro-mirrors"
    pre = "<i class='fas fa-envelope'></i>"
    weight = 6
    parent = "mailinglists"

#
# --- end Submenu Lists ---
#

# --- submenu Features ---

[[menu.main]]
    name = "在你的掌控之中"
    url = "/features/under-your-control/"
    pre = "<i class='fas fa-thumbs-up'></i></i>"
    weight = 2
    parent = "features"


[[menu.main]]
    name = "配置只需点一下"
    url = "/features/configured-with-one-click/"
    pre = "<i class='fas fa-cog'></i></i>"
    weight = 3
    parent = "features"


[[menu.main]]
    name = "适合所有人使用"
    url = "/features/useful-for-everyone/"
    pre = "<i class='fas fa-users'></i>"
    weight = 4
    parent = "features"


[[menu.main]]
    name = "很新鲜也很稳定"
    url = "/features/fresh-and-stable/"
    pre = "<i class='fas fa-paper-plane'></i>"
    weight = 5
    parent = "features"

#
# --- end submenu Features ---
#

# --- others ---
 

[[menu.footer]]
    identifier = "copyright"
    name = "2011 - 2020 Manjaro Linux"
    pre = "<i class='fa fa-copyright'></i>"
    url = "/imprint/"
    weight = 2


[[menu.footer]]
    identifier = "privacy"
    name = "隐私政策"
    pre = ""
    url = "/privacy-policy/"
    weight = 3


[[menu.footer]]
    identifier = "terms"
    name = "使用条款"
    pre = ""
    url = "/terms-of-use/"
    weight = 4

[[menu.footer]]
    identifier = "imprint"
    name = "网站说明"
    pre = ""
    url = "/imprint/"
    weight = 5


[[menu.footer]]
    identifier = "gitlab"
    pre = "<i class='fab fa-gitlab'></i>"
    url = "https://gitlab.manjaro.org"
    weight = 6

